version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: dr-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: dr
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1'
      LANG: C.UTF-8
    volumes:
      - './.docker/data/db:/var/lib/mysql'
      - './.docker/mnt:/mnt'
    ports:
      - "3308:3306"
  redis:
    image: 'redis:6-alpine'
    container_name: dr-redis
    ports:
      - 6389:6379
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - mysql
  #     - redis